name: react deploy
on: push
jobs:      
  deploy:     
    runs-on: ubuntu-latest     
    steps:         
      - name: Install dependencies
        run: npm install     

      - name: building    
        run: npm run build    

      - name: test      
        run: echo "work"
